module.exports = {
  colors: {
    col1: "white",
    col2: "#ECF2FF",
    text1: "#00334d",
    text2: "grey",
    text3: "black",
  },
  titles: {
    title1: 35,
    btntxt: 20,
  },
  btn1: {
    width: "80%",
    height: 50,
    backgroundColor: "#00334d",
    borderRadius: 10,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    elevation: 10,
    color: "white",
    marginTop: 30,
  },
  btn2: {
    width: 140,
    height: 50,
    backgroundColor: "#00334d",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    elevation: 10,
    color: "white",
    margin: 10,
  },
  btn3: {
    width: 170,
    height: 50,
    backgroundColor: "#00334d",
    borderRadius: 10,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    elevation: 10,
    color: "white",
    marginTop: 20,
  },
  btn4: {
    width: 140,
    height: 50,
    backgroundColor: "#00334d",
    borderRadius: 10,
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    elevation: 10,
    color: "white",
    marginVertical: 30,
  },
  hr80: {
    width: "80%",
    borderBottomColor: "#E0E0E0",
    borderBottomWidth: 2,
    marginBottom: 25,
    alignSelf: "center",
  },
  hr81: {
    width: "80%",
    borderBottomColor: "#E0E0E0",
    borderBottomWidth: 2,
    marginVertical: 20,
    alignSelf: "center",
  },
  veg: {
    backgroundColor: "green",
    width: 20,
    height: 20,
    borderRadius: 5,
  },
  nonveg: {
    backgroundColor: "red",
    width: 20,
    height: 20,
    borderRadius: 5,
  },
  navbtn: {
    backgroundColor: "#00334d",
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    elevation: 10,
    borderRadius: 50,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
  },
  navbtnin: {
    color: "white",
  },
  navbtnout: {
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 10,
  },
  incdecbtn: {
    backgroundColor: "#00334d",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
    width: 38,
    textAlign: "center",
    elevation: 10,
    padding: 10,
    color: "white",
    fontSize: 20,
    fontFamily: "Poppins_500Medium",
  },
  incdecinput: {
    backgroundColor: "white",
    alignItems: "center",
    textAlign: "center",
    justifyContent: "center",
    elevation: 10,
    padding: 10,
    width: "20%",
    marginHorizontal: 10,
    fontSize: 20,
  },
  incdecout: {
    flexDirection: "row",
    alignItems: "center",
    margin: 10,
  },
};
